name: Cinema Alert

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  run_cinema_alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pandas requests beautifulsoup4

    - name: Extraire IMDb ID
      run: python extract_imdb_from_letterboxd.py

    - name: Generate master CSV
      run: python generate_master_csv.py

    - name: Run cinema alert
      run: python check_cinema.py
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
